### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 3snail** [sensorsdata/sa-sdk-go#4]
env: 
window64
go1.12;
sa-sdk-go:2.0.2

result:
build error!

**C:\Users\adm\go\pkg\mod\github.com\sensorsdata\sa-sdk-go@v2.0.2+incompatible\consumers\cclogging.go:163:5: undefined: syscall.Flock     
C:\Users\adm\go\pkg\mod\github.com\sensorsdata\sa-sdk-go@v2.0.2+incompatible\consumers\cclogging.go:163:37: undefined: syscall.LOCK_EX**

**Comment by dengshiwei** [comment]
@3snail ConcurrentLoggingConsumer 不支持 Windows，Windows 下请使用 LoggingConsumer
