### ISSUE TITLE
windows编译不通过

### ISSUE THREAD

**Issue by xtakeit** [sensorsdata/sa-sdk-go#6]
神策sdk不支持windows编译。
1. 能支持windows本地测试吗。
2. 怎么做到支持windows引入包不报错.

**Comment by dengshiwei** [comment]
@xtakeit 只能修改源码，删除掉一些使用 linux 中的方法的 consumer 类

**Comment by xtakeit** [comment]
> @xtakeit 只能修改源码，删除掉一些使用 linux 中的方法的 consumer 类

好的，谢谢

**Comment by leimeng-go** [comment]
我这边目前是通过windows wsl2 ubuntu子系统开发的，后续不考虑windows平台的兼容吗？

**Comment by dengshiwei** [comment]
@leimeng-go 现阶段不会兼容，后续会考虑尝试 windows 平台兼容
