### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by softblade-c** [sensorsdata/sa-sdk-go#7]
运行测试函数，编译报错：  
# github.com/sensorsdata/sa-sdk-go/consumers
..\consumers\cclogging.go:180:5: undefined: syscall.Flock
..\consumers\cclogging.go:180:37: undefined: syscall.LOCK_EX
..\consumers\cclogging.go:184:6: undefined: syscall.Flock
..\consumers\cclogging.go:184:38: undefined: syscall.LOCK_UN
..\consumers\cclogging.go:187:5: undefined: syscall.Flock
..\consumers\cclogging.go:187:37: undefined: syscall.LOCK_UN
golang 版本：17.6
OS：Windows 10

**Comment by dengshiwei** [comment]
目前这些锁不支持在 Windows 平台上使用，只支持 Linux 和 Mac，建议您这边在 Linux 和 Mac 上使用，或者源码集成删除掉 cclogging 的代码。
